"""empty message

Revision ID: 4a19934247c3
Revises: 
Create Date: 2023-10-24 22:21:09.522430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a19934247c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livro', sa.String(length=50), nullable=False),
    sa.Column('autor', sa.String(length=20), nullable=False),
    sa.Column('ano_publicacao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblioteca')
    # ### end Alembic commands ###
